std_msgs/Header header
int8 id         # id of missionpad detected by Tello  bottom camera
float64 x       # x position of missionpad in referance to tello bottom camera
float64 y       # y position of missionpad in referance to tello bottom camera
float64 z       # z position of missionpad in referance to tello bottom camera
float64 pitch   # pitch angle of missionpad in referance to tello bottom camera
float64 roll    # roll angle of missionpad in referance to tello bottom camera
float64 yaw     # yaw angle of missionpad in referance to tello bottom camera
